"""last chance

Revision ID: 303d0d3f1e00
Revises: ef1349fcf802
Create Date: 2023-06-11 16:43:40.703342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303d0d3f1e00'
down_revision = 'ef1349fcf802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
